version: "3.8"

services:
  dilesh:
    build: .
    container_name: dilesh
    ports:
      - "2000:2000"
    volumes:
      - chroma_data:/app/chroma_db # named volume - Docker manages permissions
      - ./static:/app/static
      - ./app:/app/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VECTOR_DB_PATH=/app/chroma_db
      - UPLOAD_DIR=/app/static/documents
    user: "0:0"
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local
